# Par√¢metros para modo diferencial

gaia_bridge_node:
  ros__parameters:
    control_mode: 'differential'
    wheels_radius: 0.055
    caster_offset: 0.11
    h_positions: [0.54, 0.54, 0.54, 0.54]
    beta_angles: [0.0, 1.5708, 3.14159, -1.5708]
    update_rate: 50.0
